# Generated by Django 3.2.9 on 2021-11-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20211120_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='displayName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
