# Generated by Django 3.2.9 on 2021-11-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
