# Generated by Django 3.2.9 on 2021-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
