# Generated by Django 3.2.9 on 2021-11-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.TextField(null=True),
        ),
    ]
