# Generated by Django 3.2.9 on 2021-11-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upFile',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
