# Generated by Django 3.2.9 on 2021-11-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211114_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='threeLine',
            field=models.TextField(null=True),
        ),
    ]
